### ISSUE TITLE
After update to HA 2024.12 -> Unable to import component: No module named 'aiohuesyncbox'

### ISSUE THREAD

**Issue by sylwester-** [mvdwetering/huesyncbox#142]
**Describe the bug**
Everything worked great until upgrading to 2024.12

**To Reproduce**
upgrade to 2024.12

**Expected behavior**
integration loads

Please add the file itself (drag-and-drop in this box). Do not, copy-paste the contents here as it will make the issue unreadable

**Logging**
If there are errors in the Home Assistant logs please add them here.

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 7:51:59 PM (1 occurrences)
Last logged: 7:51:59 PM

Setup failed for custom integration 'huesyncbox': Unable to import component: No module named 'aiohuesyncbox'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/huesyncbox/__init__.py", line 6, in <module>
    import aiohuesyncbox
ModuleNotFoundError: No module named 'aiohuesyncbox'


**Environment**
Provide details about the versions you are using, which helps to reproduce and find the issue quicker.

- Home Assistant Core version: 2024.12
- Home Assistant operating environment (OS/Container/Supervised/Core): Container
- Huesyncbox integration version: latest
- Last working version (if known): this version worked with 2024.11

**Additional info**
Add any other info about the problem here.

**Comment by mvdwetering** [comment]
I don't know what could cause this. Did you try restarting HA again? (you probably did, but just to be sure)

Could you try installing it manually in the container itself by running command below and see what errors it gives. Maybe it gives some more insights.

```
python3 -m pip install aiohuesyncbox
```

**Comment by sylwester-** [comment]
I'll give it some time. Before creating the issues I did a bit of research but this is fresh.

**Comment by sylwester-** [comment]
FYI - just gave it a go with fresh install. when trying to add the integration (after download) I get: 

2025-01-03 22:26:53.959 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration huesyncbox: No module named 'aiohuesyncbox'

python -m pip install aiohuesyncbox 

fixes the problem. thanks for the mentioned issue.

**Comment by mvdwetering** [comment]
Hmm... Home Assistant should install `aiohuesyncbox` package automatically when it loads the integration. I don't understand why it is not working in some cases.

Unfortunately I am unable to reproduce this issue on my side 😞

**Comment by mvdwetering** [comment]
There has been no activity on this issue in a long time. It seems to have resolved itself for one person in #143 which is the same issue as this one. It does not seem to be a common occurrence since begin 2025, so closing this.
