### ISSUE TITLE
IndexError: list index out of range (Hue Play Gradient)

### ISSUE THREAD

**Issue by Garulf** [mvdwetering/huesyncbox#20]
Just recently the integration stopped working for some unknown reason.

I just recently (FINALLY) installed the new Hue Play Gradient lightstrip. I'm assuming the issue is related to this.

<details><summary>Error log</summary>

```
2021-05-14 01:51:09 ERROR (MainThread) [homeassistant.components.media_player] Error adding entities for domain media_player with platform huesyncbox
Traceback (most recent call last):
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
    self.async_write_ha_state()
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 370, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/components/media_player/__init__.py", line 868, in state_attributes
    value = getattr(self, attr)
  File "/Volumes/HomeAssistant/custom_components/huesyncbox/media_player.py", line 338, in media_title
    return f"{self.get_mode().capitalize()} - {self.sound_mode.capitalize()}"
  File "/Volumes/HomeAssistant/custom_components/huesyncbox/media_player.py", line 315, in sound_mode
    attributes = self.device_state_attributes
  File "/Volumes/HomeAssistant/custom_components/huesyncbox/media_player.py", line 210, in device_state_attributes
    'entertainment_area': self._get_selected_entertainment_area()
  File "/Volumes/HomeAssistant/custom_components/huesyncbox/media_player.py", line 193, in _get_selected_entertainment_area
    id = parts[1]
IndexError: list index out of range
2021-05-14 01:51:09 ERROR (MainThread) [homeassistant.components.media_player] Error while setting up huesyncbox platform for media_player
Traceback (most recent call last):
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 239, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 581, in add_to_platform_finish
    self.async_write_ha_state()
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 334, in async_write_ha_state
    self._async_write_ha_state()
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 370, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/Volumes/HomeAssistant/.venv/lib/python3.9/site-packages/homeassistant/components/media_player/__init__.py", line 868, in state_attributes
    value = getattr(self, attr)
  File "/Volumes/HomeAssistant/custom_components/huesyncbox/media_player.py", line 338, in media_title
    return f"{self.get_mode().capitalize()} - {self.sound_mode.capitalize()}"
  File "/Volumes/HomeAssistant/custom_components/huesyncbox/media_player.py", line 315, in sound_mode
    attributes = self.device_state_attributes
  File "/Volumes/HomeAssistant/custom_components/huesyncbox/media_player.py", line 210, in device_state_attributes
    'entertainment_area': self._get_selected_entertainment_area()
  File "/Volumes/HomeAssistant/custom_components/huesyncbox/media_player.py", line 193, in _get_selected_entertainment_area
    id = parts[1]
IndexError: list index out of range
```

</details>

**Comment by Garulf** [comment]
I changed line 196 to:

`id = parts[0]`

and it seems to be working fine now.
`hue_target = self._huesyncbox.api.execution.hue_target`
was returning a list with on item in the format of: `['47XX285f-XXXX-492e-XXXX-51bXXXXa590c']`

So string split was not affecting anything and a one item list was being returned.

**Comment by mvdwetering** [comment]
There seem to be some API updates.
I had already been working on some improvements and fixes for this integration and the first one was already solved when I simplified some code. I just also fixed the second issue you mentioned.

I tagged version 1.11.0 which should be available soon. Could you check if that solves the issues?

**Comment by Garulf** [comment]
I can confirm no errors and everything works beautifully after updating to 1.11.0. 

Thank you!
