### ISSUE TITLE
Can't make this integration to work

### ISSUE THREAD

**Issue by marcioibm** [mvdwetering/huesyncbox#23]
**Describe the bug**
Even though the installation goes fine, it never starts due to an error

**To Reproduce**
1. Install HACS method
2. Check for logs and seeerror

**Environment**

- Home Assistant Core version:  2021.9.5
- Home Assistant operating environment (OS/Container/Supervised/Core): OS
- Huesyncbox integration version: 1.13.0

**Additional info**

Logger: homeassistant
Source: custom_components/huesyncbox/huesyncbox.py:125
Integration: Philips Hue Play HDMI Sync Box (documentation, issues)
First occurred: 3:04:18 AM (1 occurrences)
Last logged: 3:04:18 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 171, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 710, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 524, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 529, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/huesyncbox/__init__.py", line 37, in <module>
    from .huesyncbox import PhilipsHuePlayHdmiSyncBox, async_remove_entry_from_huesyncbox
  File "/config/custom_components/huesyncbox/huesyncbox.py", line 125, in <module>
    async def async_register_aiohuesyncbox(hass, api: aiohuesyncbox.HueSyncBox):
AttributeError: module 'aiohuesyncbox' has no attribute 'HueSyncBox'

Does any see this behavior?

**Comment by mvdwetering** [comment]
Hmm, I have not seen that one and I don't really understand what is happening there.

Could you check which version of `aiohuesyncbox` is installed in the HA environment?
Also what is your Python version?

**Comment by marcioibm** [comment]
Your comment and the last update made it work! thanks for the support and for this amazing integration!

**Comment by mvdwetering** [comment]
Hmm, not sure why that update helped for this specific issue, but glad it fixed your issue :)
