### ISSUE TITLE
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'ee0a0c4da8e2078287ae04a14dea6f38'

### ISSUE THREAD

**Issue by poudenes** [mvdwetering/huesyncbox#58]
Hi There,

Installed latest Hue Box Integration and when I use the SET option I always get a error , but the SET is working on the Sync Box.

**Version v2.0.0b2**

```
2023-08-20 10:53:38.046 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'ee0a0c4da8e2078287ae04a14dea6f38'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huesyncbox/services.py", line 93, in async_set_sync_state
    coordinator = hass.data[DOMAIN][config_entry_id]
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'ee0a0c4da8e2078287ae04a14dea6f38'
2023-08-20 10:53:49.379 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'ee0a0c4da8e2078287ae04a14dea6f38'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huesyncbox/services.py", line 93, in async_set_sync_state
    coordinator = hass.data[DOMAIN][config_entry_id]
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'ee0a0c4da8e2078287ae04a14dea6f38'
```

```
service: huesyncbox.set_sync_state
data:
  sync: true
  brightness: 70
  intensity: moderate
  mode: video
  input: input1
  entertainment_area: TV room
target:
  device_id: ca734212663336331243ffd0104937dc
```

Off-topic: The solution to have this "huesyncbox" set option is great. All in one and everyone can understand this.

**Comment by poudenes** [comment]
Moved to discussion section
